apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
data:
  mongo-uri: "mongodb://admin:password@mongo-service:27017"
  mongo-db: "cicd"
  otel-endpoint: "http://otel-collector-service:4317"
