apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-job-manager
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-job-manager-binding
subjects:
  - kind: ServiceAccount
    name: cicd-server
roleRef:
  kind: Role
  name: cicd-job-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-server
  labels:
    app: cicd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-server
  template:
    metadata:
      labels:
        app: cicd-server
    spec:
      serviceAccountName: cicd-server
      containers:
        - name: cicd-server
          image: jasonte/cs7580fteam:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: mongo-uri
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: mongo-db
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: otel-endpoint
            - name: OTEL_SERVICE_NAME
              value: "cicd-server"
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-server-service
spec:
  type: NodePort
  selector:
    app: cicd-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
