apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-loki
  labels:
    app: {{ .Release.Name }}-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-loki
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-loki
    spec:
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-loki-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-loki-pvc
