apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secret
type: Opaque
data:
  mongo-root-username: {{ .Values.mongo.rootUsername | b64enc | quote }}
  mongo-root-password: {{ .Values.mongo.rootPassword | b64enc | quote }}