apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-otel-collector
  labels:
    app: {{ .Release.Name }}-otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-otel-collector
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-otel-collector
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.otelCollector.image }}
          ports:
            - containerPort: 4317
            - containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol-contrib
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-otel-collector-config
