apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    exporters:
      otlphttp/loki:
        endpoint: "http://{{ .Release.Name }}-loki-service:{{ .Values.loki.service.port }}/otlp"
      otlp/tempo:
        endpoint: "{{ .Release.Name }}-tempo-service:{{ .Values.tempo.service.grpcPort }}"
        tls:
          insecure: true
    processors:
      batch:
        timeout: 5s
        send_batch_size: 1024
      resource:
        attributes:
          - key: service.name
            value: "cicd-server"
            action: upsert
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [otlphttp/loki]
        traces:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [otlp/tempo]
