apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cicd-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-job-manager
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-job-manager-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-cicd-server
roleRef:
  kind: Role
  name: {{ .Release.Name }}-job-manager
  apiGroup: rbac.authorization.k8s.io
