apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tempo-service
spec:
  selector:
    app: {{ .Release.Name }}-tempo
  ports:
    - name: http
      port: {{ .Values.tempo.service.httpPort }}
      targetPort: 3200
    - name: grpc
      port: {{ .Values.tempo.service.grpcPort }}
      targetPort: 4317
